const Ingredient = require('./Ingredient')
const sustainableIngredients = [
    new Ingredient("Shea Butter", 9, "Moisturizing properties"),
    new Ingredient("Jojoba Oil", 8, "Hydrating and nourishing effects"),
    new Ingredient("Argan Oil", 7, "Rich in vitamins, beneficial for the skin"),
    new Ingredient("Aloe Vera", 9, "Soothing and hydrating properties"),
    new Ingredient("Rosehip Oil", 8, "Rich in antioxidants, promotes skin regeneration"),
    new Ingredient("Bamboo Extract", 8, "Natural source of silica, promotes skin health"),
    new Ingredient("Mineral Pigments", 7, "Natural coloring agents without synthetic dyes"),
    new Ingredient("Hyaluronic Acid", 7, "Hydrating and plumping effects"),
    new Ingredient("Green Tea Extract", 8, "Rich in antioxidants, anti-aging properties"),
    new Ingredient("Beeswax", 6, "Used for texture and structure, sourced sustainably"),
    new Ingredient("Cocoa Butter", 8, "Moisturizing and rich in antioxidants"),
    new Ingredient("Coconut Oil", 7, "Hydrating and nourishing effects, sourced sustainably"),
    new Ingredient("Calendula Extract", 9, "Derived from marigold flowers, has soothing properties"),
    new Ingredient("Chamomile Extract", 9, "Anti-inflammatory and calming effects"),
    new Ingredient("Olive Oil", 7, "Rich source of antioxidants and moisture, sourced sustainably"),
    new Ingredient("Algae Extract", 8, "Hydrating and skin-conditioning properties"),
    new Ingredient("Cucumber Extract", 9, "Soothing and hydrating properties"),
    new Ingredient("Sunflower Seed Oil", 7, "Rich in Vitamin E, moisturizes and nourishes the skin"),
    new Ingredient("Sesame Oil", 7, "Moisturizing and antioxidant-rich"),
    new Ingredient("Grapeseed Extract", 8, "Contains antioxidants, beneficial for the skin"),
    new Ingredient("Turmeric Extract", 8, "Anti-inflammatory and brightening properties"),
    new Ingredient("Lavender Oil", 8, "Calming and aromatic qualities, sourced organically"),
    new Ingredient("Manuka Honey", 8, "Antibacterial and moisturizing properties, sourced ethically"),
    new Ingredient("Kukui Nut Oil", 7, "Derived from the Hawaiian kukui nut, skin-conditioning effects"),
    new Ingredient("Candelilla Wax", 8, "Vegan alternative to beeswax, used for texture and structure"),
    new Ingredient("Mango Butter", 7, "Moisturizing and rich in vitamins, extracted from mango seeds"),
    new Ingredient("Evening Primrose Oil", 8, "Skin-soothing and moisturizing properties"),
    new Ingredient("Squalane", 8, "Moisturizing ingredient often derived from olives"),
    new Ingredient("Raspberry Seed Oil", 8, "Contains antioxidants and natural sun-protective properties"),
    new Ingredient("Arnica Extract", 9, "Anti-inflammatory and soothing effects"),
    new Ingredient("Licorice Root Extract", 8, "Brightening and anti-inflammatory properties"),
    new Ingredient("Carrot Seed Oil", 8, "Rich in antioxidants and vitamins, beneficial for the skin"),
    new Ingredient("Hemp Seed Oil", 8, "Moisturizing and helps regulate oil production"),
    new Ingredient("White Tea Extract", 8, "Contains antioxidants and has anti-aging properties"),
    new Ingredient("Marula Oil", 7, "Moisturizing and antioxidant effects, sourced sustainably"),
    new Ingredient("Cupuacu Butter", 7, "Derived from the seeds of the cupuacu fruit, has hydrating properties"),
    new Ingredient("Neem Oil", 8, "Antimicrobial and skin-soothing properties"),
    new Ingredient("Chia Seed Oil", 8, "Rich in omega-3 fatty acids, moisturizes and nourishes the skin"),
    new Ingredient("Red Algae Extract", 8, "Used for firming and anti-aging properties"),
    new Ingredient("Blue Tansy Oil", 8, "Calming and anti-inflammatory effects"),
    new Ingredient("Meadowfoam Seed Oil", 7, "Moisturizing and helps lock in moisture"),
    new Ingredient("Sea Buckthorn Oil", 7, "Rich in vitamins and antioxidants, moisturizes the skin"),
    new Ingredient("Frankincense Oil", 8, "Anti-aging and skin-toning properties, sourced sustainably"),
    new Ingredient("Pearl Powder", 7, "Brightening and skin-renewing effects"),
    new Ingredient("Avocado Oil", 7, "Moisturizing and rich in vitamins, sourced organically"),
    new Ingredient("Black Seed Oil", 8, "Anti-inflammatory and antioxidant properties"),
    new Ingredient("Pomegranate Seed Oil", 8, "Contains antioxidants and promotes skin elasticity"),
    new Ingredient("Cupuacu Butter", 7, "Moisturizing and nourishing, derived from the seeds of the cupuacu fruit"),
    new Ingredient("Sea Kelp Extract", 8, "Nourishing and anti-aging effects"),
    new Ingredient("Moringa Oil", 8, "Rich in vitamins and antioxidants, moisturizes the skin"),
];

const unsustainableIngredients = [
    new Ingredient("Silicones", 3, "Derived from non-renewable resources, potential environmental impacts"),
    new Ingredient("Mineral Oil", 3, "Derived from petroleum, environmentally harmful"),
    new Ingredient("Paraffin", 3, "Byproduct of petroleum refining, environmental concerns"),
    new Ingredient("PEG Compounds", 4, "Synthetic chemicals often derived from petroleum"),
    new Ingredient("Synthetic Fragrances", 4, "May contain harmful chemicals and contribute to air pollution"),
    new Ingredient("Coal Tar", 2, "Used in some hair dyes, has environmental and health concerns"),
    new Ingredient("Hydroquinone", 2, "Used in some skin-lightening products, can be harmful to the environment"),
    new Ingredient("Formaldehyde-releasing preservatives (DMDM Hydantoin, Diazolidinyl Urea)", 3, "Can release formaldehyde, a potential environmental and health concern"),
    new Ingredient("Aluminum Compounds", 4, "Found in some antiperspirants, can have environmental impacts"),
    new Ingredient("Triethanolamine", 4, "Can be derived from unsustainable sources and may have environmental concerns"),
    new Ingredient("TEA", 4, "Can be derived from unsustainable sources and may have environmental concerns"),
    new Ingredient("Polyethylene Glycol", 4, "A petroleum-based compound with potential environmental impact"),
    new Ingredient("PEG", 4, "A petroleum-based compound with potential environmental impact"),
    new Ingredient("Ethanolamines", 4, "Can be derived from non-sustainable sources"),
    new Ingredient("MEA", 4, "Can be derived from non-sustainable sources"),
    new Ingredient("DEA", 4, "Can be derived from non-sustainable sources"),
    new Ingredient("Hydroxyquinone", 2, "Used in some skincare products, may have environmental and health concerns"),
    new Ingredient("BHA", 3, "Synthetic antioxidant with potential environmental concerns"),
    new Ingredient("BHT", 3, "Synthetic antioxidant with potential environmental concerns"),
    new Ingredient("Butylated Hydroxyanisole", 3, "Synthetic antioxidant with potential environmental concerns"),
    new Ingredient("Butylated Hydroxytoluene", 3, "Synthetic antioxidant with potential environmental concerns"),
    new Ingredient("Retinyl Palmitate", 4, "A form of Vitamin A that can have environmental and health concerns"),
    new Ingredient("Methylisothiazolinone", 3, "Used as a preservative, may have environmental concerns"),
    new Ingredient("MIT", 3, "Used as a preservative, may have environmental concerns"),
    new Ingredient("Ethylparaben", 4, "A synthetic preservative with potential environmental concerns"),
    new Ingredient("Propylparaben", 4, "A synthetic preservative with potential environmental concerns"),
    new Ingredient("Butylparaben", 4, "A synthetic preservative with potential environmental concerns"),
    new Ingredient("Isobutylparaben", 4, "A synthetic preservative with potential environmental concerns"),
    new Ingredient("Butylene Glycol", 4, "Derived from petroleum, may have environmental impacts"),
    new Ingredient("Ethylene Oxide", 3, "Used in some cosmetic ingredients, associated with environmental concerns"),
    new Ingredient("PEG-40 Hydrogenated Castor Oil", 4, "May have environmental concerns"),
    new Ingredient("Dimethicone", 3, "A silicone-based ingredient with potential environmental impacts"),
    new Ingredient("Octinoxate", 2, "Found in some sunscreens, harmful to coral reefs"),
    new Ingredient("Octyl Methoxycinnamate", 2, "Found in some sunscreens, harmful to coral reefs"),
    new Ingredient("Octocrylene", 3, "Found in some sunscreens, may have environmental concerns"),
    new Ingredient("Homosalate", 3, "Found in some sunscreens, may have environmental concerns"),
    new Ingredient("Octisalate", 3, "Found in some sunscreens, may have environmental concerns"),
    new Ingredient("Octyl Salicylate", 3, "Found in some sunscreens, may have environmental concerns"),
    new Ingredient("Oxybenzone", 2, "Found in some sunscreens, harmful to coral reefs"),
    new Ingredient("Sodium Lauryl Sulfate", 3, "Surfactants with potential environmental concerns"),
    new Ingredient("Sodium Laureth Sulfate", 3, "Surfactants with potential environmental concerns"),
    new Ingredient("SLS", 3, "Surfactants with potential environmental concerns"),
    new Ingredient("SLES", 3, "Surfactants with potential environmental concerns"),
    new Ingredient("Quaternium-15", 3, "A preservative"),
];

module.exports = unsustainableIngredients, sustainableIngredients;