const Ingredient = require('./Ingredient')
const sustainableIngredients = [
    new Ingredient("Shea Butter", 9, "Moisturizing properties"),
    new Ingredient("Jojoba Oil", 8, "Hydrating and nourishing effects"),
    new Ingredient("Argan Oil", 7, "Rich in vitamins, beneficial for the skin"),
    new Ingredient("Aloe Vera", 9, "Soothing and hydrating properties"),
    new Ingredient("Rosehip Oil", 8, "Rich in antioxidants, promotes skin regeneration"),
    new Ingredient("Bamboo Extract", 8, "Natural source of silica, promotes skin health"),
    new Ingredient("Mineral Pigments", 7, "Natural coloring agents without synthetic dyes"),
    new Ingredient("Hyaluronic Acid", 7, "Hydrating and plumping effects"),
    new Ingredient("Green Tea Extract", 8, "Rich in antioxidants, anti-aging properties"),
    new Ingredient("Beeswax", 6, "Used for texture and structure, sourced sustainably"),
    new Ingredient("Cocoa Butter", 8, "Moisturizing and rich in antioxidants"),
    new Ingredient("Coconut Oil", 7, "Hydrating and nourishing effects, sourced sustainably"),
    new Ingredient("Calendula Extract", 9, "Derived from marigold flowers, has soothing properties"),
    new Ingredient("Chamomile Extract", 9, "Anti-inflammatory and calming effects"),
    new Ingredient("Olive Oil", 7, "Rich source of antioxidants and moisture, sourced sustainably"),
    new Ingredient("Algae Extract", 8, "Hydrating and skin-conditioning properties"),
    new Ingredient("Cucumber Extract", 9, "Soothing and hydrating properties"),
    new Ingredient("Sunflower Seed Oil", 7, "Rich in Vitamin E, moisturizes and nourishes the skin"),
    new Ingredient("Sesame Oil", 7, "Moisturizing and antioxidant-rich"),
    new Ingredient("Grapeseed Extract", 8, "Contains antioxidants, beneficial for the skin"),
    new Ingredient("Turmeric Extract", 8, "Anti-inflammatory and brightening properties"),
    new Ingredient("Lavender Oil", 8, "Calming and aromatic qualities, sourced organically"),
    new Ingredient("Manuka Honey", 8, "Antibacterial and moisturizing properties, sourced ethically"),
    new Ingredient("Kukui Nut Oil", 7, "Derived from the Hawaiian kukui nut, skin-conditioning effects"),
    new Ingredient("Candelilla Wax", 8, "Vegan alternative to beeswax, used for texture and structure"),
    new Ingredient("Mango Butter", 7, "Moisturizing and rich in vitamins, extracted from mango seeds"),
    new Ingredient("Evening Primrose Oil", 8, "Skin-soothing and moisturizing properties"),
    new Ingredient("Squalane", 8, "Moisturizing ingredient often derived from olives"),
    new Ingredient("Raspberry Seed Oil", 8, "Contains antioxidants and natural sun-protective properties"),
    new Ingredient("Arnica Extract", 9, "Anti-inflammatory and soothing effects"),
    new Ingredient("Licorice Root Extract", 8, "Brightening and anti-inflammatory properties"),
    new Ingredient("Carrot Seed Oil", 8, "Rich in antioxidants and vitamins, beneficial for the skin"),
    new Ingredient("Hemp Seed Oil", 8, "Moisturizing and helps regulate oil production"),
    new Ingredient("White Tea Extract", 8, "Contains antioxidants and has anti-aging properties"),
    new Ingredient("Marula Oil", 7, "Moisturizing and antioxidant effects, sourced sustainably"),
    new Ingredient("Cupuacu Butter", 7, "Derived from the seeds of the cupuacu fruit, has hydrating properties"),
    new Ingredient("Neem Oil", 8, "Antimicrobial and skin-soothing properties"),
    new Ingredient("Chia Seed Oil", 8, "Rich in omega-3 fatty acids, moisturizes and nourishes the skin"),
    new Ingredient("Red Algae Extract", 8, "Used for firming and anti-aging properties"),
    new Ingredient("Blue Tansy Oil", 8, "Calming and anti-inflammatory effects"),
    new Ingredient("Meadowfoam Seed Oil", 7, "Moisturizing and helps lock in moisture"),
    new Ingredient("Sea Buckthorn Oil", 7, "Rich in vitamins and antioxidants, moisturizes the skin"),
    new Ingredient("Frankincense Oil", 8, "Anti-aging and skin-toning properties, sourced sustainably"),
    new Ingredient("Pearl Powder", 7, "Brightening and skin-renewing effects"),
    new Ingredient("Avocado Oil", 7, "Moisturizing and rich in vitamins, sourced organically"),
    new Ingredient("Black Seed Oil", 8, "Anti-inflammatory and antioxidant properties"),
    new Ingredient("Pomegranate Seed Oil", 8, "Contains antioxidants and promotes skin elasticity"),
    new Ingredient("Cupuacu Butter", 7, "Moisturizing and nourishing, derived from the seeds of the cupuacu fruit"),
    new Ingredient("Sea Kelp Extract", 8, "Nourishing and anti-aging effects"),
    new Ingredient("Moringa Oil", 8, "Rich in vitamins and antioxidants, moisturizes the skin"),
    new Ingredient("Silicones", 3, "Derived from non-renewable resources, potential environmental impacts"),
    new Ingredient("Mineral Oil", 3, "Derived from petroleum, environmentally harmful"),
    new Ingredient("Paraffin", 3, "Byproduct of petroleum refining, environmental concerns"),
    new Ingredient("PEG Compounds", 4, "Synthetic chemicals often derived from petroleum"),
    new Ingredient("Synthetic Fragrances", 4, "May contain harmful chemicals and contribute to air pollution"),
    new Ingredient("Coal Tar", 2, "Used in some hair dyes, has environmental and health concerns"),
    new Ingredient("Hydroquinone", 2, "Used in some skin-lightening products, can be harmful to the environment"),
    new Ingredient("Formaldehyde-releasing preservatives (DMDM Hydantoin, Diazolidinyl Urea)", 3, "Can release formaldehyde, a potential environmental and health concern"),
    new Ingredient("Aluminum Compounds", 4, "Found in some antiperspirants, can have environmental impacts"),
    new Ingredient("Triethanolamine", 4, "Can be derived from unsustainable sources and may have environmental concerns"),
    new Ingredient("TEA", 4, "Can be derived from unsustainable sources and may have environmental concerns"),
    new Ingredient("Polyethylene Glycol", 4, "A petroleum-based compound with potential environmental impact"),
    new Ingredient("PEG", 4, "A petroleum-based compound with potential environmental impact"),
    new Ingredient("Ethanolamines", 4, "Can be derived from non-sustainable sources"),
    new Ingredient("MEA", 4, "Can be derived from non-sustainable sources"),
    new Ingredient("DEA", 4, "Can be derived from non-sustainable sources"),
    new Ingredient("Hydroxyquinone", 2, "Used in some skincare products, may have environmental and health concerns"),
    new Ingredient("BHA", 3, "Synthetic antioxidant with potential environmental concerns"),
    new Ingredient("BHT", 3, "Synthetic antioxidant with potential environmental concerns"),
    new Ingredient("Butylated Hydroxyanisole", 3, "Synthetic antioxidant with potential environmental concerns"),
    new Ingredient("Butylated Hydroxytoluene", 3, "Synthetic antioxidant with potential environmental concerns"),
    new Ingredient("Retinyl Palmitate", 4, "A form of Vitamin A that can have environmental and health concerns"),
    new Ingredient("Methylisothiazolinone", 3, "Used as a preservative, may have environmental concerns"),
    new Ingredient("MIT", 3, "Used as a preservative, may have environmental concerns"),
    new Ingredient("Ethylparaben", 4, "A synthetic preservative with potential environmental concerns"),
    new Ingredient("Propylparaben", 4, "A synthetic preservative with potential environmental concerns"),
    new Ingredient("Butylparaben", 4, "A synthetic preservative with potential environmental concerns"),
    new Ingredient("Isobutylparaben", 4, "A synthetic preservative with potential environmental concerns"),
    new Ingredient("Butylene Glycol", 4, "Derived from petroleum, may have environmental impacts"),
    new Ingredient("Ethylene Oxide", 3, "Used in some cosmetic ingredients, associated with environmental concerns"),
    new Ingredient("PEG-40 Hydrogenated Castor Oil", 4, "May have environmental concerns"),
    new Ingredient("Hydrogenated Castor Oil", 4, "May have environmental concerns"),
    new Ingredient("Dimethicone", 3, "A silicone-based ingredient with potential environmental impacts"),
    new Ingredient("Octinoxate", 2, "Found in some sunscreens, harmful to coral reefs"),
    new Ingredient("Octyl Methoxycinnamate", 2, "Found in some sunscreens, harmful to coral reefs"),
    new Ingredient("Octocrylene", 3, "Found in some sunscreens, may have environmental concerns"),
    new Ingredient("Homosalate", 3, "Found in some sunscreens, may have environmental concerns"),
    new Ingredient("Octisalate", 3, "Found in some sunscreens, may have environmental concerns"),
    new Ingredient("Octyl Salicylate", 3, "Found in some sunscreens, may have environmental concerns"),
    new Ingredient("Oxybenzone", 2, "Found in some sunscreens, harmful to coral reefs"),
    new Ingredient("Sodium Lauryl Sulfate", 3, "Surfactants with potential environmental concerns"),
    new Ingredient("Sodium Laureth Sulfate", 3, "Surfactants with potential environmental concerns"),
    new Ingredient("SLS", 3, "Surfactants with potential environmental concerns"),
    new Ingredient("SLES", 3, "Surfactants with potential environmental concerns"),
    new Ingredient("Quaternium-15", 3, "A preservative"),
    new Ingredient("Tiger Grass", 9, "Typically sustainable, depending on sourcing and cultivation methods. Known for skin-soothing properties."),
    new Ingredient("Humectant Blend (Glycerin and Hyaluronic Acid)", 7, "Glycerin is commonly plant-derived. Hyaluronic acid can be produced through biotechnological methods, but large-scale production may involve energy-intensive processes."),
    new Ingredient("Rich Emollients (Squalane, Vitamin E, Safflower, and Avocado Oils)", 8, "Generally plant-derived and rich in nutrients. Squalane, if sourced sustainably, can have a lower environmental impact."),
    new Ingredient("Water/Aqua/Eau", 9, "Water is neutral, but the environmental impact may arise from sourcing and purification processes."),
    new Ingredient("Ethylhexyl Palmitate", 4, "Often derived from palm oil, associated with deforestation and environmental concerns."),
    new Ingredient("Glycerin", 7, "Commonly plant-derived, but the score can vary based on sourcing practices."),
    new Ingredient("Isododecane", 3, "Synthetic hydrocarbon, potentially derived from petroleum, contributing to environmental concerns."),
    new Ingredient("Diethylhexyl Carbonate", 4, "Typically synthetic and may have environmental considerations."),
    new Ingredient("Isohexadecane", 3, "Synthetic hydrocarbon with potential environmental impacts."),
    new Ingredient("Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate", 6, "Generally considered safer than traditional emulsifiers, but the environmental impact depends on the specific formulation and production methods."),
    new Ingredient("Polymethylsilsesquioxane", 3, "Synthetic ingredient that may have environmental concerns."),
    new Ingredient("Trimethylsiloxysilicate", 3, "Silicone-based compound with potential environmental impacts."),
    new Ingredient("Sodium Chloride", 5, "Generally considered safe, but large-scale extraction methods may have environmental consequences."),
    new Ingredient("C13-15 Alkane", 3, "Synthetic hydrocarbon that may have environmental considerations."),
    new Ingredient("Sodium Hyaluronate", 7, "The salt form of hyaluronic acid, and the score depends on the sourcing method."),
    new Ingredient("Squalane", 7, "Squalane from plant sources is more sustainable than that derived from sharks, but the score can vary based on sourcing."),
    new Ingredient("Niacinamide", 8, "Generally considered safe, with a lower environmental impact compared to some other ingredients."),
    new Ingredient("Centella Asiatica Leaf Extract", 9, "Typically sustainable, especially if sourced responsibly."),
    new Ingredient("Tocopheryl Acetate", 6, "Vitamin E is generally safe, but sourcing practices can influence the score."),
    new Ingredient("Tocopherol", 6, "Similar to Tocopheryl Acetate, the environmental score depends on sourcing."),
    new Ingredient("Persea Gratissima (Avocado) Oil", 8, "Avocado oil is plant-derived and nutrient-rich, but the score can vary based on sourcing practices."),
    new Ingredient("Camellia Sinensis Leaf Extract", 8, "Generally sustainable, but the environmental impact may depend on cultivation methods."),
    new Ingredient("Carthamus Tinctorius (Safflower) Seed Oil", 8, "Safflower oil is plant-derived, and the score can vary based on sourcing practices."),
    new Ingredient("Glycine Soja (Soybean) Oil", 7, "Soybean oil is plant-derived, but concerns may arise from large-scale monoculture."),
    new Ingredient("Ethylhexylglycerin", 4, "Often synthetic and may have environmental concerns."),
    new Ingredient("Hydrogenated Vegetable Oil", 5, "The environmental impact depends on the specific vegetable oil used and the hydrogenation process."),
    new Ingredient("Silica", 3, "Generally safe, but the environmental impact may arise from mining practices."),
    new Ingredient("Alumina", 3, "An oxide derived from bauxite, with potential environmental concerns related to mining."),
    new Ingredient("Disteardimonium Hectorite", 4, "Synthetic compound that may have environmental considerations."),
    new Ingredient("Magnesium Oxide", 3, "Generally safe, but the environmental impact may arise from mining."),
    new Ingredient("Propylene Carbonate", 4, "Synthetic compound with potential environmental concerns."),
    new Ingredient("Zinc Stearate", 4, "Often synthetic and may have environmental considerations."),
    new Ingredient("Boron Nitride", 5, "Generally safe, but the environmental impact may arise from mining practices."),
    new Ingredient("Sodium Benzoate", 5, "A preservative, and the score depends on manufacturing practices."),
    new Ingredient("Potassium Sorbate", 5, "Generally considered safe, but the environmental impact depends on production methods."),
    new Ingredient("Zinc Oxide", 9, "Shields skin from damaging UV rays and is gentle enough for sensitive skin."),
    new Ingredient("Squalane", 8, "Leaves skin appearing softer, smoother, and plumped up."),
    new Ingredient("Antioxidant Complex (Vitamin E and Ethyl Ferulate)", 8, "Helps protect skin against free-radical damage."),
    new Ingredient("Water", 9, "Hydrating and essential for skincare formulations."),
    new Ingredient("C12-15 Alkyl Benzoate", 3, "Synthetic ingredient that may have environmental considerations."),
    new Ingredient("Sorbitan Oleate Decylglucoside Crosspolymer", 3, "Synthetic ingredient with potential environmental impacts."),
    new Ingredient("Argania Spinosa Kernel Oil", 7, "Rich in vitamins, beneficial for the skin."),
    new Ingredient("Tocopheryl Acetate", 6, "Vitamin E is generally safe, but sourcing practices can influence the score."),
    new Ingredient("Ammonium Acryloyldimethyltaurate/VP Copolymer", 3, "Synthetic copolymer with potential environmental impacts."),
    new Ingredient("Glycerin", 7, "Commonly plant-derived, but the score can vary based on sourcing practices."),
    new Ingredient("Caramel", 3, "Colorant that may have environmental concerns."),
    new Ingredient("Polyester-5", 3, "Synthetic ingredient with potential environmental impacts."),
    new Ingredient("Butyrospermum Parkii (Shea) Butter Extract", 9, "Moisturizing properties."),
    new Ingredient("Bisabolol", 9, "Anti-inflammatory and soothing effects."),
    new Ingredient("Phospholipids", 6, "Generally safe, but the environmental impact may depend on sourcing practices."),
    new Ingredient("Tocopherol", 6, "Similar to Tocopheryl Acetate, the environmental score depends on sourcing."),
    new Ingredient("Ethyl Ferulate", 6, "The score depends on the sourcing method."),
    new Ingredient("Urea", 4, "Synthetic compound with potential environmental concerns."),
    new Ingredient("Ethylhexylglycerin", 4, "Often synthetic and may have environmental concerns."),
    new Ingredient("Gluconolactone", 5, "A polyhydroxy acid that may have environmental considerations."),
    new Ingredient("Triethoxycaprylylsilane", 3, "Silicone-based compound with potential environmental impacts."),
    new Ingredient("Dimethicone", 3, "A silicone-based ingredient with potential environmental impacts."),
    new Ingredient("Sodium Chloride", 5, "Generally considered safe, but large-scale extraction methods may have environmental consequences."),
    new Ingredient("Benzyl Alcohol", 4, "Preservative with potential environmental concerns."),
    new Ingredient("Sodium Benzoate", 5, "A preservative, and the score depends on manufacturing practices."),
    new Ingredient("Sorbic Acid", 4, "Preservative with potential environmental concerns."),
    new Ingredient("Chlorphenesin", 4, "Synthetic compound that may have environmental considerations."),
    new Ingredient("Phenoxyethanol", 4, "Preservative with potential environmental concerns."),
    new Ingredient("Rice Bran Oil", 8, "Rich in antioxidants and moisturizes the skin."),
    new Ingredient("Cetyl Alcohol", 3, "A fatty alcohol often derived from palm oil, potential environmental concerns."),
    new Ingredient("Panthenol", 7, "Provitamin B5, hydrates and improves skin elasticity."),
    new Ingredient("Cetearyl Glucoside", 6, "Plant-derived emulsifier, relatively sustainable."),
    new Ingredient("Saccharide Isomerate", 8, "Plant-derived moisturizing ingredient."),
    new Ingredient("Lauryl Glucoside", 5, "Mild surfactant, potential environmental concerns."),
    new Ingredient("Caprylic/Capric Triglyceride", 6, "Derived from coconut oil, moderate sustainability."),
    new Ingredient("Lactic Acid", 7, "Mild exfoliant, score varies based on source."),
    new Ingredient("Xanthan Gum", 5, "Common thickener, potential environmental impacts."),
    new Ingredient("Beta-Glucan", 9, "Derived from oats, known for soothing and moisturizing properties."),
    new Ingredient("Polyquaternium-7", 4, "Synthetic polymer with potential environmental concerns."),
    new Ingredient("Salicylic Acid", 6, "Beta-hydroxy acid, score varies based on source and concentration."),
    new Ingredient("Ethylhexyl Methoxycinnamate", 2, "UV filter, potential environmental concerns and harmful to coral reefs."),
    new Ingredient("Cetearyl Alcohol", 5, "Fatty alcohol, score depends on the source."),
    new Ingredient("Polyglyceryl-3 Diisostearate", 7, "Plant-derived emulsifier."),
    new Ingredient("Coco-Caprylate", 6, "Derived from coconut oil, moderate sustainability."),
    new Ingredient("Tetrasodium EDTA", 2, "Chelating agent, potential environmental concerns."),
    new Ingredient("Citric Acid", 7, "Derived from citrus fruits, score varies based on source."),
    new Ingredient("Polyglyceryl-10 Stearate", 8, "Plant-derived emulsifier."),
    new Ingredient("Retinol", 4, "Vitamin A derivative, potential environmental concerns."),
    new Ingredient("Cucumis Sativus (Cucumber) Fruit Extract", 9, "Soothing and hydrating properties."),
    new Ingredient("Polyglyceryl-6 Stearate", 8, "Plant-derived emulsifier."),
    new Ingredient("Ceteareth-20", 4, "Emulsifying agent, potential environmental concerns."),
    new Ingredient("Sodium Ascorbyl Phosphate", 8, "Stable form of Vitamin C, score varies based on source."),
    new Ingredient("Bis-PEG-18 Methyl Ether Dimethyl Silane", 3, "Silicone-based compound with potential environmental impacts."),
    new Ingredient("Phytosterols", 9, "Plant-derived compounds with moisturizing and skin-barrier enhancing properties."),
    new Ingredient("Polyglyceryl-4 Caprate", 8, "Plant-derived emulsifier."),
    new Ingredient("Ascorbyl Palmitate", 5, "Vitamin C ester, score varies based on source."),
    new Ingredient("Polyglyceryl-4 Laurate", 8, "Plant-derived emulsifier."),
    new Ingredient("Trehalose", 7, "Sugar-derived ingredient with moisturizing properties."),
    new Ingredient("Polyglyceryl-6 Laurate", 8, "Plant-derived emulsifier."),
    new Ingredient("Polyglyceryl-10 Laurate", 8, "Plant-derived emulsifier."),
    new Ingredient("Sodium Cocoyl Isethionate", 5, "Mild surfactant, potential environmental concerns."),
    new Ingredient("Polyquaternium-10", 4, "Cationic polymer with potential environmental concerns."),
    new Ingredient("Lecithin", 6, "Often derived from soy, score varies based on source."),
    new Ingredient("Polyglyceryl-4 Oleate", 8, "Plant-derived emulsifier."),
    new Ingredient("Decyl Glucoside", 5, "Mild surfactant, potential environmental concerns."),
    new Ingredient("Polyglyceryl-6 Oleate", 8, "Plant-derived emulsifier."),
    new Ingredient("Sodium Cocoyl Glycinate", 5, "Mild surfactant, potential environmental concerns."),
    new Ingredient("Polyglyceryl-10 Oleate", 8, "Plant-derived emulsifier."),
    new Ingredient("Cocamidopropyl Betaine", 4, "Surfactant, potential environmental concerns."),
    new Ingredient("Polyglyceryl-2 Dipolyhydroxystearate", 8, "Plant-derived emulsifier."),
    new Ingredient("Sodium Lauroyl Methyl Isethionate", 5, "Mild surfactant, potential environmental concerns."),
    new Ingredient("Polyglyceryl-3 Polyricinoleate", 8, "Plant-derived emulsifier."),
    new Ingredient("Behenyl Alcohol", 5, "Fatty alcohol, score depends on the source."),
    new Ingredient("Polyglyceryl-4 Diisostearate", 8, "Plant-derived emulsifier."),
    new Ingredient("Polyglyceryl-10 Diisostearate", 8, "Plant-derived emulsifier."),
    new Ingredient("Polyglyceryl-2 Stearate", 8, "Plant-derived emulsifier."),
    new Ingredient("Polyglyceryl-3 Stearate", 8, "Plant-derived emulsifier."),
    new Ingredient("Polyglyceryl-10 Decaoleate", 8, "Plant-derived emulsifier."),
    new Ingredient("Polyglyceryl-4 Decaoleate", 8, "Plant-derived emulsifier."),
    new Ingredient("Polyglyceryl-2 Oleate", 8, "Plant-derived emulsifier."),
    new Ingredient("Polyglyceryl-3 Oleate", 8, "Plant-derived emulsifier."),
    new Ingredient("Lactic Acid", 7, "Exfoliating agent derived from sour milk."),
    new Ingredient("Salicylic Acid", 6, "Beta hydroxy acid with exfoliating properties."),
    new Ingredient("Citric Acid", 7, "Alpha hydroxy acid derived from citrus fruits."),
    new Ingredient("Ascorbic Acid (Vitamin C)", 8, "Antioxidant with skin-brightening properties."),
    new Ingredient("Panthenol (Vitamin B5)", 8, "Humectant with moisturizing properties."),
    new Ingredient("Niacinamide (Vitamin B3)", 8, "Vitamin that helps improve skin texture and tone."),
    new Ingredient("Retinol (Vitamin A1)", 7, "Skin-renewing and anti-aging ingredient."),
    new Ingredient("Hyaluronic Acid", 7, "Humectant that retains skin moisture."),
    new Ingredient("Glycolic Acid", 6, "Alpha hydroxy acid with exfoliating properties."),
    new Ingredient("Ferulic Acid", 7, "Antioxidant that enhances the stability of other vitamins."),
    new Ingredient("Kojic Acid", 5, "Skin-lightening agent, but may have stability concerns."),
    new Ingredient("Alpha Arbutin", 6, "Skin-brightening agent."),
    new Ingredient("Beta-Glucans", 8, "Soothing and hydrating agent."),
    new Ingredient("Ceramides", 8, "Lipids that help retain skin moisture."),
    new Ingredient("Peptides", 7, "Amino acid chains with anti-aging properties."),
    new Ingredient("Caffeine", 6, "Stimulant with potential benefits for reducing puffiness."),
    new Ingredient("Allantoin", 7, "Soothing and skin-conditioning agent."),
    new Ingredient("Centella Asiatica Extract", 8, "Soothing and anti-inflammatory ingredient."),
    new Ingredient("Green Tea Extract", 8, "Antioxidant with anti-aging properties."),
    new Ingredient("Licorice Root Extract", 8, "Brightening and anti-inflammatory properties."),
    new Ingredient("Sodium Ascorbyl Phosphate", 7, "Stable form of Vitamin C with antioxidant properties."),
    new Ingredient("Madecassoside", 9, "Derived from Centella Asiatica, known for wound healing."),
    new Ingredient("Resveratrol", 7, "Antioxidant found in red wine, with anti-aging properties."),
    new Ingredient("Adenosine", 7, "Improves the appearance of fine lines and wrinkles."),
    new Ingredient("AHA/BHA Blend", 6, "Combination of alpha and beta hydroxy acids for exfoliation."),
    new Ingredient("Zinc Oxide", 9, "Mineral sunscreen ingredient with UV protection."),
    new Ingredient("Glycerin", 7, "Humectant that attracts and retains moisture."),
    new Ingredient("Jojoba Oil", 8, "Hydrating and nourishing effects."),
    new Ingredient("Squalane", 8, "Moisturizing ingredient often derived from olives."),
    new Ingredient("Rosehip Oil", 8, "Rich in antioxidants, promotes skin regeneration."),
    new Ingredient("Chamomile Extract", 9, "Anti-inflammatory and calming effects."),
    new Ingredient("Sea Buckthorn Oil", 7, "Rich in vitamins and antioxidants, moisturizes the skin."),
    new Ingredient("Niacinamide", 8, "Vitamin B3 that helps improve skin texture."),
    new Ingredient("Alpha-Lipoic Acid", 7, "Antioxidant with potential anti-aging benefits."),
    new Ingredient("Argireline", 6, "Peptide that may reduce the appearance of wrinkles."),
    new Ingredient("Coenzyme Q10", 7, "Antioxidant that supports skin health."),
    new Ingredient("Matrixyl", 7, "Peptide blend for anti-aging benefits."),
    new Ingredient("Copper Peptides", 7, "Peptides with potential skin-renewing properties."),
    new Ingredient("Ceramide NP", 8, "Ceramide for skin barrier support."),
    new Ingredient("Glycyrrhizinic Acid", 8, "Derived from licorice root, has anti-inflammatory properties."),
    new Ingredient("Fermented Ingredients", 8, "Ingredients processed through fermentation for potential skin benefits."),
    new Ingredient("Retinyl Palmitate", 6, "Form of Vitamin A with potential anti-aging benefits."),
    new Ingredient("Hemp Seed Oil", 8, "Moisturizing and helps regulate oil production."),
    new Ingredient("Tetrahexyldecyl Ascorbate", 8, "Stable form of Vitamin C with antioxidant properties."),
    new Ingredient("Phytoestrogens", 7, "Plant-derived compounds with potential skin benefits."),
    new Ingredient("Vitamin E Acetate", 7, "Stable form of Vitamin E with antioxidant properties."),
    new Ingredient("Palmitoyl Oligopeptide", 7, "Peptide with potential anti-aging benefits."),
    new Ingredient("Palmitoyl Tetrapeptide-7", 7, "Peptide with potential anti-aging benefits."),
    new Ingredient("Probiotics", 8, "Live bacteria with potential skin-balancing benefits."),
    new Ingredient("Zinc PCA", 7, "Zinc salt with potential sebum-regulating properties."),
    new Ingredient("Bakuchiol", 8, "Natural alternative to retinol with anti-aging benefits."),
    new Ingredient("Rosemary Extract", 8, "Antioxidant with potential skin-soothing properties."),
    new Ingredient("Mica", 5, "Natural mineral with environmental concerns in mining."),
    new Ingredient("Talc", 3, "Commonly mined mineral with potential health and environmental concerns."),
    new Ingredient("Zinc Stearate", 4, "May be synthetic or derived from palm oil with potential environmental impacts."),
    new Ingredient("Boron Nitride", 5, "Generally safe, but the environmental impact may arise from mining practices."),
    new Ingredient("Nylon-12", 4, "Synthetic polymer with potential environmental concerns."),
    new Ingredient("Silica", 3, "Generally safe, but the environmental impact may arise from mining practices."),
    new Ingredient("Octyldodecyl Stearoyl Stearate", 6, "Generally safe, but the environmental impact may vary."),
    new Ingredient("Diisostearyl Malate", 4, "May be synthetic with potential environmental concerns."),
    new Ingredient("Sodium Dehydroacetate", 5, "Synthetic preservative with potential environmental concerns."),
    new Ingredient("Phenoxyethanol", 4, "Synthetic preservative with potential environmental concerns."),
    new Ingredient("Sorbic Acid", 5, "Synthetic preservative with potential environmental concerns."),
    new Ingredient("Triethoxycaprylylsilane", 4, "Silicone-based compound with potential environmental impacts."),
    new Ingredient("Cellulose", 5, "Derived from plant sources, but the environmental impact depends on sourcing."),
    new Ingredient("Polyethylene", 3, "Synthetic polymer with potential environmental concerns."),
    new Ingredient("Titanium Dioxide (CI 77891)", 4, "Commonly used mineral pigment, but concerns may arise from production processes."),
    new Ingredient("Manganese Violet (CI 77742)", 5, "May contain synthetic colorants with potential environmental impacts."),
    new Ingredient("Iron Oxides (CI 77491, CI 77492)", 4, "Commonly used mineral pigments, but concerns may arise from production processes."),
    new Ingredient("Yellow 5 Lake (CI 19140)", 5, "Synthetic colorant with potential environmental concerns."),
    new Ingredient("Dimethicone", 3, "A silicone-based ingredient with potential environmental impacts."),
    new Ingredient("Calcium Aluminum Borosilicate", 5, "May contain synthetic colorants with potential environmental impacts."),
    new Ingredient("Caprylic/Capric Triglyceride", 6, "Generally safe, but the environmental impact may vary."),
    new Ingredient("Octyldodecyl Stearoyl Stearate", 6, "Generally safe, but the environmental impact may vary."),
    new Ingredient("Magnesium Myristate", 4, "May be synthetic with potential environmental concerns."),
    new Ingredient("Diisostearyl Malate", 4, "May be synthetic with potential environmental concerns."),
    new Ingredient("Silica", 3, "Generally safe, but the environmental impact may arise from mining practices."),
    new Ingredient("HDI/Trimethylol Hexyllactone Crosspolymer", 4, "May be synthetic with potential environmental concerns."),
    new Ingredient("Caprylyl Glycol", 5, "Synthetic preservative with potential environmental concerns."),
    new Ingredient("1,2-Hexanediol", 4, "Synthetic preservative with potential environmental concerns."),
    new Ingredient("Tin Oxide", 5, "May contain synthetic colorants with potential environmental impacts."),
    new Ingredient("Acrylates Copolymer", 4, "May be synthetic with potential environmental concerns."),
    new Ingredient("Isododecane", 3, "Synthetic hydrocarbon with potential environmental impacts."),
    new Ingredient("Titanium Dioxide (CI 77891)", 4, "Commonly used mineral pigment, but concerns may arise from production processes."),
    new Ingredient("Iron Oxides (CI 77491, CI 77492, CI 77499)", 4, "Commonly used mineral pigments, but concerns may arise from production processes."),
    new Ingredient("Bismuth Oxychloride (CI 77163)", 5, "May contain synthetic colorants with potential environmental impacts."),
    new Ingredient("Talc", 3, "Commonly mined mineral with potential health and environmental concerns."),
    new Ingredient("Boron Nitride", 5, "Generally safe, but the environmental impact may arise from mining practices."),
    new Ingredient("Nylon-12", 4, "Synthetic polymer with potential environmental concerns."),
    new Ingredient("Silica", 3, "Generally safe, but the environmental impact may arise from mining practices."),
    new Ingredient("Mica", 5, "Natural mineral with environmental concerns in mining."),
    new Ingredient("Cellulose", 5, "Derived from plant sources, but the environmental impact depends on sourcing."),
    new Ingredient("Octyldodecyl Stearoyl Stearate", 6, "Generally safe, but the environmental impact may vary."),
    new Ingredient("Polyethylene", 3, "Synthetic polymer with potential environmental concerns."),
    new Ingredient("Zinc Stearate", 4, "May be synthetic or derived from palm oil with potential environmental impacts."),
    new Ingredient("Diisostearyl Malate", 4, "May be synthetic with potential environmental concerns."),
    new Ingredient("Sodium Dehydroacetate", 5, "Synthetic preservative with potential environmental concerns."),
    new Ingredient("Phenoxyethanol", 4, "Synthetic preservative with potential environmental concerns."),
    new Ingredient("Sorbic Acid", 5, "Synthetic preservative with potential environmental concerns."),
    new Ingredient("Manganese Violet (CI 77742)", 5, "May contain synthetic colorants with potential environmental impacts."),
    new Ingredient("Iron Oxides (CI 77491, CI 77492, CI 77499)", 4, "Commonly used mineral pigments, but concerns may arise from production processes."),
    new Ingredient("Titanium Dioxide (CI 77891)", 4, "Commonly used mineral pigment, but concerns may arise from production processes."),
    new Ingredient("Carmine (CI 75470)", 5, "Natural colorant with potential environmental concerns."),
    new Ingredient("Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate", 6,
        "Generally considered safer than traditional emulsifiers, but the environmental impact depends on the specific formulation and production methods."
    )
];

module.exports = sustainableIngredients;